project_name: "Render Lib Off"
project_type: library
include_devcontainer: false
include_docs_site: false
include_pr_title_check: false
include_integration_tests: false
include_contract_tests: false
include_test_helpers: false
include_renovate: false
include_extras_example: false
include_pr_labeler: false
include_discussions: false
include_pypi_publish: false
